CREATE TABLE user_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,

    CONSTRAINT fk_user_role_role
                       FOREIGN KEY (role_id)
                       REFERENCES roles(id)
                       ON DELETE CASCADE,
    CONSTRAINT fk_user_role_user
                       FOREIGN KEY (user_id)
                       REFERENCES users(id)
                       ON DELETE CASCADE
);

CREATE INDEX idx_user_role_user_id
ON user_role(user_id);

CREATE INDEX idx_user_role_role_id
ON user_role(role_id);

CREATE UNIQUE INDEX uq_user_role_active
ON user_role(user_id, role_id)
WHERE deleted_at is NULL;